<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-14T22:57:21 IST" name="Default suite" finished-at="2024-11-14T22:57:56 IST" duration-ms="34852">
    <groups>
    </groups>
    <test started-at="2024-11-14T22:57:21 IST" name="Default test" finished-at="2024-11-14T22:57:56 IST" duration-ms="34852">
      <class name="test.SwagLabLoginTest">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:test.SwagLabLoginTest@5b12b668]" started-at="2024-11-14T22:57:22 IST" name="LaunchApplication" finished-at="2024-11-14T22:57:38 IST" duration-ms="15820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="verifyIfUserIsAbleToLoginWithValidCredentials()[pri:0, instance:test.SwagLabLoginTest@5b12b668]" started-at="2024-11-14T22:57:38 IST" name="verifyIfUserIsAbleToLoginWithValidCredentials" finished-at="2024-11-14T22:57:43 IST" duration-ms="5417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIfUserIsAbleToLoginWithValidCredentials -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:test.SwagLabLoginTest@5b12b668]" started-at="2024-11-14T22:57:43 IST" name="LaunchApplication" finished-at="2024-11-14T22:57:52 IST" duration-ms="9282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="verifyIfWarningMessageIsDisplayedForLockedUser()[pri:0, instance:test.SwagLabLoginTest@5b12b668]" started-at="2024-11-14T22:57:52 IST" name="verifyIfWarningMessageIsDisplayedForLockedUser" finished-at="2024-11-14T22:57:55 IST" duration-ms="3047" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.SwagLabLoginTest.verifyIfWarningMessageIsDisplayedForLockedUser(SwagLabLoginTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIfWarningMessageIsDisplayedForLockedUser -->
      </class> <!-- test.SwagLabLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
